### PR TITLE
Manage files and sc-utility.php

### PR DESCRIPTION
**Pull request by bahiirwa**
This PR seeks to:

- Clean the `sc-utility.php` file
- Add a file `includes/admin-emails.php` to manage email stuff
- Add a file `includes/other-settings.php` to handle any new settings that cannot categorized in the other files.
- Code refactor to make the code smaller and more readable.

### CODE REVIEW

**Comment by bahiirwa** [comment]
Still work in progress

**Comment by simplycomputing** [comment]
OK. This may be beyond me. You have changed 8 files and there are now conflicts. I don't really know where to go from here.

**Comment by bahiirwa** [comment]
Let me fix the conflicts. It’s probably because of the first merges. You can test the branch before merging to see if all is well.

**Comment by simplycomputing** [comment]
I don't know how to test it.

**Comment by bahiirwa** [comment]
You can test this download zip on a staging site. I have fixed the merge conflicts before zipping this.

[sc-utility-managge-files.zip](https://github.com/simplycomputing/sc-utility/files/4143691/sc-utility-managge-files.zip)

**Pull request merged**
